# name: try
# key: try
# --
try {
	$1
} catch(${2:Exception} ${3:e}) {
	$4
}